import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav"
import Results from "../components/Results";
import MovieListResult from "../types/MovieResultsList";
import APIResult from "../types/APIResult";
import data from "../util/requests";

type HomeProps = {
  results: MovieListResult[];
};

const Home = ({ results }: HomeProps) => {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results}/>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const genre = context.query.genre as string;

  const request: APIResult = await fetch(
    `https://api.themoviedb.org/3${data[genre]?.url || data.fetchTrending.url}`
  )
    .then((res) => res.json())
    .catch((err) => console.log(err));

  const results = request.results as MovieListResult[];

  return {
    props: {
      results,
    },
  };
};